Add Support for Feign (Declarative Service Call)
Use @FeignClient to replace RestTemplate.getForEntity()

Issue: with @RequestParam, @RequestHeader, @RequestBody, sometimes the request will return 200, however it will return 500, log as follows, need to figure out why.

feign.FeignException: status 404 reading FeignHelloService#hello1(String); content:
{"timestamp":1518882838545,"status":404,"error":"Not Found","message":"No message available","path":"/hello1"}